export const LOGIN = 'REDUCERS/VIEW/LOGIN/登录';
export const LISTMACHINE = 'REDUCERS/VIEW/LISTMATHINE/机器列表';
export const LISTNETWORK = 'REDUCERS/VIEW/LISTNETWORK/网点服务列表';
export const LISTSERVICE = 'REDUCERS/VIEW/LISTSERVICE/维修服务列表';
export const LISTORDER = 'REDUCERS/VIEW/LISTORDER/订单列表';
